### ISSUE TITLE
Pip or Conda install

### ISSUE THREAD

**Issue by maray** [ChileanVirtualObservatory/pycupid#1]
Ok. I want to be a user of pycupid. How do I install it? (I actually need this, not just messing around).

**Comment by cvalenzu** [comment]
Using `pip install pycupid` in Linux distributions (need to upload mac wheels)
https://pypi.python.org/pypi/pycupid/0.1.0

**Comment by cvalenzu** [comment]
Mac Wheels uploaded, need to test them and look into conda.
