### ISSUE TITLE
Pip install failed

### ISSUE THREAD

**Issue by zychen-astro** [ChileanVirtualObservatory/pycupid#16]
Hello all,
pip install pycupid in my computer returns the following errors (both in Ubuntu 18.04 and MacOS Mojave):

Collecting pycupid
  Using cached https://files.pythonhosted.org/packages/98/a0/d7408b274fa75e5c92c699cd987a0abe24e93ac42603112f16cd7c5ccc37/pycupid-0.1.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/\*\*\*/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i74ehsac/pycupid/setup.py'"'"'; \_\_file\_\_='"'"'/tmp/pip-install-i74ehsac/pycupid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(\_\_file\_\_;code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, \_\_file\_\_, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-i74ehsac/pycupid/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i74ehsac/pycupid/setup.py", line 131, in <module>
        extensions = cythonize(extensions)
      File "/home/\*\*\*/miniconda3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
        aliases=aliases)
      File "/home/***/miniconda3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 810, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/\*\*\*/miniconda3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 109, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pycupid/pycupid.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Environment:
Python 3.7.4
pip 19.2.3
Minconda
OS: Ubuntu 18.04 & MacOS Mojave

Tried download the package and pip install .
Failed either with plenty of errors.

Any suggestions? Thanks a lot!

**Comment by yy1021805450** [comment]
Me too, but on windows10 ......

**Comment by GiantMolecularCloud** [comment]
Same problem for me. Installing from source with 
```
git clone https://github.com/ChileanVirtualObservatory/pycupid.git
python setup.py build install
``` 
fails with the error
```
error in pycupid setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
```
The third option using
```
pip install git+https://github.com/ChileanVirtualObservatory/pycupid.git
```
also fails with another error message
```
ERROR: Command errored out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.
```

This package is not useable! Please fix.

**Comment by GiantMolecularCloud** [comment]
The various installation methods work just fine if run in the correct python version (2.7, 3.4, 3.5, 3.6). Version 3.7+ are not supported.
Installation attempts on unsupported version should be prevented with PR #18.

**Comment by Git-blip-design** [comment]
为什么在3.6版本也安装失败，哦对了我创建的是虚拟环境，和这个有关系吗
