### ISSUE TITLE
Pycupid Wheel size

### ISSUE THREAD

**Issue by cvalenzu** [ChileanVirtualObservatory/pycupid#3]
After compiling all starlink and including the shared libraries needed for the clumping algorithms the package size is 32 mb

Using `strip -S --strip-unneeded --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag star/libs/*` on all starlink shared libraries it reduced to 9.4mb but we lost all the debug info.

The smaller package looks great for distributing, I don't think we need to debug the starlink libraries.

**Comment by Nesus** [comment]
Resolved on commit ae8d243988ba8393b1a4eafd32f78944423a3310

**Comment by cvalenzu** [comment]
Resolved in ae8d243988ba8393b1a4eafd32f78944423a3310
