### ISSUE TITLE
Add Libgfortran

### ISSUE THREAD

**Issue by cvalenzu** [ChileanVirtualObservatory/pycupid#8]
Cupid libraries uses `libgfortran3.so` we need to add it to the packaging.

**Comment by mavillan** [comment]
The error: `ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory` raises in ubuntu and manjaro distributions (not in fedora).

**Comment by cvalenzu** [comment]
Added ligfortran to wheel in https://github.com/ChileanVirtualObservatory/pycupid/commit/51eeec70bc8f4eb58a1d6c205cfdba789d600123 using auditwheel.
